### ISSUE TITLE
Won't work in React v16

### ISSUE THREAD

**Issue by gfx** [Deschtex/html2react#25]
This is because React v16 no longer provide `*DOMPropertyConfig`s.

Issued in the react repo: https://github.com/facebook/react/issues/10391

**Comment by gfx** [comment]
Closed with a suggestion:

> While it is a bit annoying I encourage you to just copy and paste them (and update if you notice changes on our side).

**Comment by Deschtex** [comment]
Thanks for looking into this, @gfx. Yea, it seems I have to copy the properties and keep it updated manually. Will prepare a branch for it.

**Comment by Deschtex** [comment]
Closed by #27
