### ISSUE TITLE
Do not parse child nodes if the only child node is a text node

### ISSUE THREAD

**Issue by Deschtex** [Deschtex/html2react#5]

**Comment by Deschtex** [comment]
Partially done by https://github.com/Deschtex/html2react/commit/0ad740fcbfda74989e663e1572fec5a57c2d9d8e#diff-5331c6d9a6e7006f165da02ffb94886cR13. It is now up to the React version used by the consumer. React v15 does not render `span`s for text nodes.

**Comment by xaviervia** [comment]
So `html2react` works with v15+? Fine by me.

**Comment by Deschtex** [comment]
It does. I just had to remove the explicit creation of `span`s for text nodes.
